services:
  - type: web
    name: anti-counterfeit-system
    env: docker
    plan: free
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
